*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_JOB $7;
label IMP_JOB = 'Imputed JOB';
IMP_JOB = JOB;
if JOB = '' then IMP_JOB = 'Other';
length IMP_REASON $7;
label IMP_REASON = 'Imputed REASON';
IMP_REASON = REASON;
if REASON = '' then IMP_REASON = 'DebtCon';
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_CLAGE = 'Imputed CLAGE';
IMP_CLAGE = CLAGE;
if missing(CLAGE) then IMP_CLAGE = 181.15305208;
label IMP_CLNO = 'Imputed CLNO';
IMP_CLNO = CLNO;
if missing(CLNO) then IMP_CLNO = 21.277078966;
label IMP_DEBTINC = 'Imputed DEBTINC';
IMP_DEBTINC = DEBTINC;
if missing(DEBTINC) then IMP_DEBTINC = 33.786945547;
label IMP_DELINQ = 'Imputed DELINQ';
IMP_DELINQ = DELINQ;
if missing(DELINQ) then IMP_DELINQ = 0.4622255303;
label IMP_DEROG = 'Imputed DEROG';
IMP_DEROG = DEROG;
if missing(DEROG) then IMP_DEROG = 0.2409592691;
label IMP_MORTDUE = 'Imputed MORTDUE';
IMP_MORTDUE = MORTDUE;
if missing(MORTDUE) then IMP_MORTDUE = 73574.90271;
label IMP_NINQ = 'Imputed NINQ';
IMP_NINQ = NINQ;
if missing(NINQ) then IMP_NINQ = 1.1569852941;
label IMP_VALUE = 'Imputed VALUE';
IMP_VALUE = VALUE;
if missing(VALUE) then IMP_VALUE = 102480.61861;
label IMP_YOJ = 'Imputed YOJ';
IMP_YOJ = YOJ;
if missing(YOJ) then IMP_YOJ = 8.868358373;
